# DATA PREPROCESSING/DATA PREPARATION

1. Data Cleaning - drop, fillna with mean, median, mode Imputation, changing dtype
2. Data Transformation
    * If data is CONTINUOUS = Standard Scaler, MinMaxScaler, Robust Scaler
    * If data is DISCRETE   = Label Encoder, One hot Encoder

### 1. Busniness Understanding

In [1]:
#

### 2. Data Collection

#### 2.1 Import necessary libirary and dataset

In [2]:
import pandas as pd

weather_data = pd.read_csv('environmental_data.csv')

### 3. Data Understanding

#### 3.1 Perform initial analysis on data

In [3]:
print("Shape:",weather_data.shape)
print("Data types: ",weather_data.dtypes)
print("Duplicates:",weather_data.duplicated().unique())
print("Nulls:",weather_data.isna().sum())
weather_data.head()

Shape: (158, 10)
Data types:  Unnamed: 0      int64
Ozone         float64
Solar.R       float64
Wind          float64
Temp C         object
Month          object
Day             int64
Year            int64
Temp            int64
Weather        object
dtype: object
Duplicates: [False]
Nulls: Unnamed: 0     0
Ozone         38
Solar.R        7
Wind           0
Temp C         0
Month          0
Day            0
Year           0
Temp           0
Weather        3
dtype: int64

   Unnamed: 0  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0           1   41.0    190.0   7.4     67     5    1  2010    67       S
1           2   36.0    118.0   8.0     72     5    2  2010    72       C
2           3   12.0    149.0  12.6     74     5    3  2010    74      PS
3           4   18.0    313.0  11.5     62     5    4  2010    62       S
4           5    NaN      NaN  14.3     56     5    5  2010    56       S

In [4]:
weather_data.describe(include='all')

,Unnamed: 0,Ozone,Solar.R,Wind,Temp C,Month,Day,Year,Temp,Weather
count,158.000000,120.000000,151.000000,158.000000,158,158,158.000000,158.0,158.000000,155
unique,NaN,NaN,NaN,NaN,41,6,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,81,9,NaN,NaN,NaN,S
freq,NaN,NaN,NaN,NaN,11,34,NaN,NaN,NaN,59
mean,79.500000,41.583333,185.403974,9.957595,NaN,NaN,16.006329,2010.0,77.727848,NaN
std,45.754781,32.620709,88.723103,3.511261,NaN,NaN,8.997166,0.0,9.377877,NaN
min,1.000000,1.000000,7.000000,1.700000,NaN,NaN,1.000000,2010.0,56.000000,NaN
25%,40.250000,18.000000,119.000000,7.400000,NaN,NaN,8.000000,2010.0,72.000000,NaN
50%,79.500000,30.500000,197.000000,9.700000,NaN,NaN,16.000000,2010.0,78.500000,NaN
75%,118.750000,61.500000,257.000000,11.875000,NaN,NaN,24.000000,2010.0,84.000000,NaN
max,158.000000,168.000000,334.000000,20.700000,NaN,NaN,31.000000,2010.0,97.000000,NaN

In [5]:
weather_data['Weather'].unique()

array(['S', 'C', 'PS', nan], dtype=object)

### 4. Data Preparation/preprocessing

#### Stage 1
Data Cleaning - drop, fillna with mean, median, mode Imputation, changing dtype

In [6]:
# TEMP C and TEMP both are same column

weather_data.drop(labels= ['Unnamed: 0','Temp C'],axis= 1,inplace= True)
#del weather_data['Temp C']
weather_data

     Ozone  Solar.R  Wind Month  Day  Year  Temp Weather
0     41.0    190.0   7.4     5    1  2010    67       S
1     36.0    118.0   8.0     5    2  2010    72       C
2     12.0    149.0  12.6     5    3  2010    74      PS
3     18.0    313.0  11.5     5    4  2010    62       S
4      NaN      NaN  14.3     5    5  2010    56       S
..     ...      ...   ...   ...  ...   ...   ...     ...
153   41.0    190.0   7.4     5    1  2010    67       C
154   30.0    193.0   6.9     9   26  2010    70      PS
155    NaN    145.0  13.2     9   27  2010    77       S
156   14.0    191.0  14.3     9   28  2010    75       S
157   18.0    131.0   8.0     9   29  2010    76       C

[158 rows x 8 columns]

In [7]:
# removed unwanted columns - 'Unnamed: 0' and'Temp C'

In [8]:
weather_data.isna().sum()

Ozone      38
Solar.R     7
Wind        0
Month       0
Day         0
Year        0
Temp        0
Weather     3
dtype: int64

In [9]:
38/158

0.24050632911392406

In [10]:
# We are droping this Ozone column, as 24% of the data is NaN.

#we can replace it with mean also deponds upon the confirmation from the business

In [11]:
del weather_data['Ozone']

In [12]:
weather_data[weather_data['Solar.R'].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
4       NaN  14.3     5    5  2010    56       S
5       NaN  14.9     5    6  2010    66       C
10      NaN   6.9     5   11  2010    74       C
26      NaN   8.0     5   27  2010    57      PS
95      NaN   6.9     8    4  2010    86     NaN
96      NaN   7.4     8    5  2010    85       S
97      NaN   4.6     8    6  2010    87       C

In [13]:
weather_data.groupby('Weather')['Solar.R'].mean().round()

Weather
C     192.0
PS    174.0
S     193.0
Name: Solar.R, dtype: float64

In [14]:
weather_data['Solar.R'] =weather_data.groupby('Weather')['Solar.R'].transform(lambda x:
                                                                     x.fillna(x.mean()
                                                                         .round()))

In [15]:
weather_data.isna().sum()

Solar.R    3
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    3
dtype: int64

In [16]:
weather_data[weather_data['Solar.R'].isna()]

    Solar.R  Wind Month  Day  Year  Temp Weather
87      NaN  12.0     7   27  2010    86     NaN
93      NaN  13.8     8    2  2010    81     NaN
95      NaN   6.9     8    4  2010    86     NaN

In [18]:
weather_data.dropna(inplace= True)

In [19]:
weather_data.isna().sum()

Solar.R    0
Wind       0
Month      0
Day        0
Year       0
Temp       0
Weather    0
dtype: int64

In [22]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month       object
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

In [23]:
weather_data['Month'].unique()

array(['5', 'May', '6', '7', '8', '9'], dtype=object)

In [24]:
weather_data['Month'].replace(to_replace="May",value=5,inplace = True)

C:\Users\Senthil\AppData\Local\Temp\ipykernel_26932\275203963.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  weather_data['Month'].replace(to_replace="May",value=5,inplace = True)

In [27]:
weather_data['Month'] = weather_data['Month'].astype('int')

In [28]:
weather_data.dtypes

Solar.R    float64
Wind       float64
Month        int64
Day          int64
Year         int64
Temp         int64
Weather     object
dtype: object

#### Stage 2 Data Transformation
- If data is CONTINUOUS = Standard Scaler, MinMaxScaler, Robust Scaler
- If data is DISCRETE = Label Encoder, One hot Encoder

In [29]:
weather_data_copy = weather_data.copy()

##### LabelEncoder

In [32]:
from sklearn.preprocessing import LabelEncoder
l_encoder = LabelEncoder()
weather_data_copy['Weather'] = l_encoder.fit_transform(weather_data_copy['Weather'])

In [33]:
weather_data_copy

     Solar.R  Wind  Month  Day  Year  Temp  Weather
0      190.0   7.4      5    1  2010    67        2
1      118.0   8.0      5    2  2010    72        0
2      149.0  12.6      5    3  2010    74        1
3      313.0  11.5      5    4  2010    62        2
4      193.0  14.3      5    5  2010    56        2
..       ...   ...    ...  ...   ...   ...      ...
153    190.0   7.4      5    1  2010    67        0
154    193.0   6.9      9   26  2010    70        1
155    145.0  13.2      9   27  2010    77        2
156    191.0  14.3      9   28  2010    75        2
157    131.0   8.0      9   29  2010    76        0

[155 rows x 7 columns]

In [34]:
#We can use this copy to perform further steps

In [39]:
weather_data_copy_1 = weather_data.copy()

##### One Hot Encoder
- pandas - pd.get_dummies()
- sklean - OneHotEncoder

In [40]:
weather_data_copy_1 = pd.get_dummies(data = weather_data_copy_1,
                                    columns= ['Weather'],
                                    dtype= 'int')
weather_data_copy_1

     Solar.R  Wind  Month  Day  Year  Temp  Weather_C  Weather_PS  Weather_S
0      190.0   7.4      5    1  2010    67          0           0          1
1      118.0   8.0      5    2  2010    72          1           0          0
2      149.0  12.6      5    3  2010    74          0           1          0
3      313.0  11.5      5    4  2010    62          0           0          1
4      193.0  14.3      5    5  2010    56          0           0          1
..       ...   ...    ...  ...   ...   ...        ...         ...        ...
153    190.0   7.4      5    1  2010    67          1           0          0
154    193.0   6.9      9   26  2010    70          0           1          0
155    145.0  13.2      9   27  2010    77          0           0          1
156    191.0  14.3      9   28  2010    75          0           0          1
157    131.0   8.0      9   29  2010    76          1           0          0

[155 rows x 9 columns]

In [42]:
weather_data_copy_2 = weather_data.copy()

In [51]:
from sklearn.preprocessing import OneHotEncoder
oh_encoder =OneHotEncoder(sparse_output = False)

In [55]:
encoder_array = oh_encoder.fit_transform(weather_data_copy_2[['Weather']])

### How to choose between Label Encoder and One Hot Encoder?

#### Input feature:
Based on whether it is **Parametric or a Non Parametric Model**, we will choosing between LE or OHE.
* For **Parametric Models** - better to go with **OHE.**
* For **Non-Parametric Models** - always go with **Label Encoding.**

#### Output feature:
Always the output feature, it must be **Label Encoder.**