### 1. Busniness Understanding

In [1]:
# Predicting the user will pay the credit card bill next month or not

### 2. Data Collection

#### 2.1 Import necessory libirary and datasets

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from sklearn.ensemble import GradientBoostingClassifier,AdaBoostClassifier

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier

from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,roc_auc_score

cc_data = pd.read_csv("credit_card_clean.csv")

### 3. Data Undestanding

#### 3.1 Perform initial analysis on the data

In [3]:
cc_data.shape

(30000, 25)

In [4]:
cc_data.isna().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [5]:
cc_data.duplicated().unique()

array([False])

In [6]:
cc_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX           object
EDUCATION     object
MARRIAGE      object
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

In [7]:
cc_data.head(10)

,ID,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,1,20000.0,female,university,married,24,2,2,-1,-1,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,2,120000.0,female,university,single,26,-1,2,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,3,90000.0,female,university,single,34,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,4,50000.0,female,university,married,37,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,5,50000.0,male,university,married,57,-1,0,-1,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
5,6,50000.0,male,grad,single,37,0,0,0,0,...,19394.0,19619.0,20024.0,2500.0,1815.0,657.0,1000.0,1000.0,800.0,0
6,7,500000.0,male,grad,single,29,0,0,0,0,...,542653.0,483003.0,473944.0,55000.0,40000.0,38000.0,20239.0,13750.0,13770.0,0
7,8,100000.0,female,university,single,23,0,-1,-1,0,...,221.0,-159.0,567.0,380.0,601.0,0.0,581.0,1687.0,1542.0,0
8,9,140000.0,female,highschool,married,28,0,0,2,0,...,12211.0,11793.0,3719.0,3329.0,0.0,432.0,1000.0,1000.0,1000.0,0
9,10,20000.0,male,highschool,single,35,-2,-2,-2,-2,...,0.0,13007.0,13912.0,0.0,0.0,0.0,13007.0,1122.0,0.0,0

In [8]:
del cc_data["ID"]

In [9]:
cc_data

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_1,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,DEFAULT
0,20000.0,female,university,married,24,2,2,-1,-1,-2,...,0.0,0.0,0.0,0.0,689.0,0.0,0.0,0.0,0.0,1
1,120000.0,female,university,single,26,-1,2,0,0,0,...,3272.0,3455.0,3261.0,0.0,1000.0,1000.0,1000.0,0.0,2000.0,1
2,90000.0,female,university,single,34,0,0,0,0,0,...,14331.0,14948.0,15549.0,1518.0,1500.0,1000.0,1000.0,1000.0,5000.0,0
3,50000.0,female,university,married,37,0,0,0,0,0,...,28314.0,28959.0,29547.0,2000.0,2019.0,1200.0,1100.0,1069.0,1000.0,0
4,50000.0,male,university,married,57,-1,0,-1,0,0,...,20940.0,19146.0,19131.0,2000.0,36681.0,10000.0,9000.0,689.0,679.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,220000.0,male,highschool,married,39,0,0,0,0,0,...,88004.0,31237.0,15980.0,8500.0,20000.0,5003.0,3047.0,5000.0,1000.0,0
29996,150000.0,male,highschool,single,43,-1,-1,-1,-1,0,...,8979.0,5190.0,0.0,1837.0,3526.0,8998.0,129.0,0.0,0.0,0
29997,30000.0,male,university,single,37,4,3,2,-1,0,...,20878.0,20582.0,19357.0,0.0,0.0,22000.0,4200.0,2000.0,3100.0,1
29998,80000.0,male,highschool,married,41,1,-1,0,0,0,...,52774.0,11855.0,48944.0,85900.0,3409.0,1178.0,1926.0,52964.0,1804.0,1
29999,50000.0,male,university,married,46,0,0,0,0,0,...,36535.0,32428.0,15313.0,2078.0,1800.0,1430.0,1000.0,1000.0,1000.0,1

In [10]:
cc_data_copy01 = cc_data.copy()

#### 3.2 Data Transformation

In [11]:
encoder = LabelEncoder()
cc_data_copy01["SEX"] = encoder.fit_transform(cc_data_copy01["SEX"])
cc_data_copy01["EDUCATION"] = encoder.fit_transform(cc_data_copy01["EDUCATION"])
cc_data_copy01["MARRIAGE"] = encoder.fit_transform(cc_data_copy01["MARRIAGE"])

In [12]:
cc_data_copy01.dtypes

LIMIT_BAL    float64
SEX            int64
EDUCATION      int64
MARRIAGE       int64
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

### 4. Data Preparation

In [13]:
X = cc_data_copy01.drop('DEFAULT',axis = 1) #cc_data_copy01.iloc[:,0:23]
y = cc_data_copy01['DEFAULT']

In [14]:
 X_train, X_test, y_train, y_test  = train_test_split(X,y,train_size=0.8,
                                                      random_state=39,
                                                      shuffle=True,
                                                      stratify=y)

### 5. Model Building

In [15]:
ada_boost = AdaBoostClassifier()
grad_boost = GradientBoostingClassifier(n_estimators=50)
xg_boost = XGBClassifier(n_estimators=50)
lg_boost = LGBMClassifier(n_estimators=50)

### 6. Model Training

In [16]:
%%time
ada_boost.fit(X_train,y_train)

CPU times: total: 4.34 s
Wall time: 4.59 s

AdaBoostClassifier()

In [17]:
%%time
grad_boost.fit(X_train,y_train)

CPU times: total: 10.5 s
Wall time: 10.9 s

GradientBoostingClassifier(n_estimators=50)

In [18]:
%%time
xg_boost.fit(X_train,y_train)

CPU times: total: 3.02 s
Wall time: 595 ms

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=50,
              n_jobs=None, num_parallel_tree=None, ...)

In [19]:
%%time
lg_boost.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 5309, number of negative: 18691
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.007721 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 3260
[LightGBM] [Info] Number of data points in the train set: 24000, number of used features: 23
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.221208 -> initscore=-1.258639
[LightGBM] [Info] Start training from score -1.258639
CPU times: total: 1.77 s
Wall time: 230 ms

LGBMClassifier(n_estimators=50)

### 7. Model Testing

In [20]:
y_pred_adb = ada_boost.predict(X_test)
y_pred_gb = grad_boost.predict(X_test)
y_pred_xgb = xg_boost.predict(X_test)
y_pred_lgb = lg_boost.predict(X_test)

### 8. Model Evaluation

In [21]:
print("ADA BOOST")
print(confusion_matrix(y_test,y_pred_adb))
print(classification_report(y_test,y_pred_adb))
print("Accuracy score",accuracy_score(y_test,y_pred_adb))
print("ROC AUC score",roc_auc_score(y_test,y_pred_adb))

ADA BOOST
[[4473  200]
 [ 901  426]]
              precision    recall  f1-score   support

           0       0.83      0.96      0.89      4673
           1       0.68      0.32      0.44      1327

    accuracy                           0.82      6000
   macro avg       0.76      0.64      0.66      6000
weighted avg       0.80      0.82      0.79      6000

Accuracy score 0.8165
ROC AUC score 0.6391129048514361

In [22]:
print("GRADIENT BOOST")
print(confusion_matrix(y_test,y_pred_gb))
print(classification_report(y_test,y_pred_gb))
print("Accuracy score",accuracy_score(y_test,y_pred_gb))
print("ROC AUC score",roc_auc_score(y_test,y_pred_gb))

GRADIENT BOOST
[[4447  226]
 [ 867  460]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4673
           1       0.67      0.35      0.46      1327

    accuracy                           0.82      6000
   macro avg       0.75      0.65      0.67      6000
weighted avg       0.80      0.82      0.79      6000

Accuracy score 0.8178333333333333
ROC AUC score 0.6491418175989276

In [23]:
print("Extreme GRADIENT BOOST")
print(confusion_matrix(y_test,y_pred_xgb))
print(classification_report(y_test,y_pred_xgb))
print(accuracy_score(y_test,y_pred_xgb))
print(roc_auc_score(y_test,y_pred_xgb))

Extreme GRADIENT BOOST
[[4417  256]
 [ 847  480]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4673
           1       0.65      0.36      0.47      1327

    accuracy                           0.82      6000
   macro avg       0.75      0.65      0.68      6000
weighted avg       0.80      0.82      0.80      6000

0.8161666666666667
0.6534676832437494

In [24]:
print("Light GRADIENT BOOST")
print(confusion_matrix(y_test,y_pred_lgb))
print(classification_report(y_test,y_pred_lgb))
print(accuracy_score(y_test,y_pred_lgb))
print(roc_auc_score(y_test,y_pred_lgb))

Light GRADIENT BOOST
[[4437  236]
 [ 858  469]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      4673
           1       0.67      0.35      0.46      1327

    accuracy                           0.82      6000
   macro avg       0.75      0.65      0.68      6000
weighted avg       0.80      0.82      0.80      6000

0.8176666666666667
0.6514629489002787

In [25]:
accuracy_score(y_test,y_pred_lgb)

0.8176666666666667

## Feature Importance

In [34]:
boost_dict = {"Features":X.columns,
    "AdaBoost":ada_boost.feature_importances_,
"GradientBoost":grad_boost.feature_importances_,
"ExtremeBoost":xg_boost.feature_importances_,
"LightBoost":lg_boost.feature_importances_}

In [36]:
feature_importance_list = pd.DataFrame(boost_dict)

In [55]:
feature_importance_list.sort_values("AdaBoost",ascending = False)[["Features","AdaBoost"]].head(10)

     Features  AdaBoost
5       PAY_1  0.513414
17   PAY_AMT1  0.091755
0   LIMIT_BAL  0.056585
7       PAY_3  0.051612
18   PAY_AMT2  0.047240
11  BILL_AMT1  0.041522
9       PAY_5  0.040600
19   PAY_AMT3  0.032933
6       PAY_2  0.022936
10      PAY_6  0.021001

In [56]:
feature_importance_list[["Features","AdaBoost"]]

     Features  AdaBoost
0   LIMIT_BAL  0.056585
1         SEX  0.014049
2   EDUCATION  0.000000
3    MARRIAGE  0.015450
4         AGE  0.000000
5       PAY_1  0.513414
6       PAY_2  0.022936
7       PAY_3  0.051612
8       PAY_4  0.010050
9       PAY_5  0.040600
10      PAY_6  0.021001
11  BILL_AMT1  0.041522
12  BILL_AMT2  0.017479
13  BILL_AMT3  0.000000
14  BILL_AMT4  0.000000
15  BILL_AMT5  0.000000
16  BILL_AMT6  0.000000
17   PAY_AMT1  0.091755
18   PAY_AMT2  0.047240
19   PAY_AMT3  0.032933
20   PAY_AMT4  0.019324
21   PAY_AMT5  0.004050
22   PAY_AMT6  0.000000

In [51]:
feature_importance_list.sort_values("GradientBoost",ascending = False)["Features"].head(10)

5         PAY_1
6         PAY_2
7         PAY_3
11    BILL_AMT1
0     LIMIT_BAL
9         PAY_5
17     PAY_AMT1
19     PAY_AMT3
18     PAY_AMT2
8         PAY_4
Name: Features, dtype: object

In [52]:
feature_importance_list.sort_values("ExtremeBoost",ascending = False)["Features"].head(10)

5         PAY_1
6         PAY_2
7         PAY_3
8         PAY_4
9         PAY_5
19     PAY_AMT3
10        PAY_6
0     LIMIT_BAL
11    BILL_AMT1
18     PAY_AMT2
Name: Features, dtype: object

In [53]:
feature_importance_list.sort_values("LightBoost",ascending = False)["Features"].head(10)

11    BILL_AMT1
0     LIMIT_BAL
18     PAY_AMT2
19     PAY_AMT3
17     PAY_AMT1
4           AGE
20     PAY_AMT4
12    BILL_AMT2
22     PAY_AMT6
5         PAY_1
Name: Features, dtype: object